




.build/mega2560-5058f1af/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/mega2560-5058f1af/src
	@echo [93msrc/sketch.ino[0m
	@/usr/local/bin/ino preproc -d . -o $@ $^


all : .build/mega2560-5058f1af/src/sketch.cpp
	@true

