


























.build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp.o : /usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp
	@echo [93mAdafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp[0m
	@mkdir -p .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/utility
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp
include .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp.d

.build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp.o : /usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp
	@echo [93mAdafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp[0m
	@mkdir -p .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp
include .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp.d








.build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/libAdafruit_Motor_Shield_V2_Library-master.a : .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/utility/Adafruit_MS_PWMServoDriver.cpp.o .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/Adafruit_MotorShield.cpp.o
	@echo [92mLinking libAdafruit_Motor_Shield_V2_Library-master.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^








.build_ano/mega2560/Wire/utility/twi.c.o : /usr/share/arduino/libraries/Wire/utility/twi.c
	@echo [93mWire/utility/twi.c[0m
	@mkdir -p .build_ano/mega2560/Wire/utility
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/libraries/Wire/utility/twi.c
include .build_ano/mega2560/Wire/utility/twi.c.d






.build_ano/mega2560/Wire/Wire.cpp.o : /usr/share/arduino/libraries/Wire/Wire.cpp
	@echo [93mWire/Wire.cpp[0m
	@mkdir -p .build_ano/mega2560/Wire
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Wire/Wire.cpp
include .build_ano/mega2560/Wire/Wire.cpp.d








.build_ano/mega2560/Wire/libWire.a : .build_ano/mega2560/Wire/utility/twi.c.o .build_ano/mega2560/Wire/Wire.cpp.o
	@echo [92mLinking libWire.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^








.build_ano/mega2560/arduino/wiring_digital.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build_ano/mega2560/arduino/wiring_digital.c.d

.build_ano/mega2560/arduino/wiring.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build_ano/mega2560/arduino/wiring.c.d

.build_ano/mega2560/arduino/WInterrupts.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build_ano/mega2560/arduino/WInterrupts.c.d

.build_ano/mega2560/arduino/wiring_analog.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build_ano/mega2560/arduino/wiring_analog.c.d

.build_ano/mega2560/arduino/wiring_shift.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build_ano/mega2560/arduino/wiring_shift.c.d

.build_ano/mega2560/arduino/avr-libc/realloc.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build_ano/mega2560/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build_ano/mega2560/arduino/avr-libc/realloc.c.d

.build_ano/mega2560/arduino/avr-libc/malloc.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build_ano/mega2560/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build_ano/mega2560/arduino/avr-libc/malloc.c.d

.build_ano/mega2560/arduino/wiring_pulse.c.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc"   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build_ano/mega2560/arduino/wiring_pulse.c.d






.build_ano/mega2560/arduino/Print.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build_ano/mega2560/arduino/Print.cpp.d

.build_ano/mega2560/arduino/HID.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build_ano/mega2560/arduino/HID.cpp.d

.build_ano/mega2560/arduino/USBCore.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build_ano/mega2560/arduino/USBCore.cpp.d

.build_ano/mega2560/arduino/Stream.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build_ano/mega2560/arduino/Stream.cpp.d

.build_ano/mega2560/arduino/WMath.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build_ano/mega2560/arduino/WMath.cpp.d

.build_ano/mega2560/arduino/IPAddress.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build_ano/mega2560/arduino/IPAddress.cpp.d

.build_ano/mega2560/arduino/WString.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build_ano/mega2560/arduino/WString.cpp.d

.build_ano/mega2560/arduino/CDC.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build_ano/mega2560/arduino/CDC.cpp.d

.build_ano/mega2560/arduino/HardwareSerial.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build_ano/mega2560/arduino/HardwareSerial.cpp.d

.build_ano/mega2560/arduino/new.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build_ano/mega2560/arduino/new.cpp.d

.build_ano/mega2560/arduino/main.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build_ano/mega2560/arduino/main.cpp.d

.build_ano/mega2560/arduino/Tone.cpp.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build_ano/mega2560/arduino/Tone.cpp.d








.build_ano/mega2560/arduino/libarduino.a : .build_ano/mega2560/arduino/wiring_digital.c.o .build_ano/mega2560/arduino/wiring.c.o .build_ano/mega2560/arduino/WInterrupts.c.o .build_ano/mega2560/arduino/wiring_analog.c.o .build_ano/mega2560/arduino/wiring_shift.c.o .build_ano/mega2560/arduino/avr-libc/realloc.c.o .build_ano/mega2560/arduino/avr-libc/malloc.c.o .build_ano/mega2560/arduino/wiring_pulse.c.o .build_ano/mega2560/arduino/Print.cpp.o .build_ano/mega2560/arduino/HID.cpp.o .build_ano/mega2560/arduino/USBCore.cpp.o .build_ano/mega2560/arduino/Stream.cpp.o .build_ano/mega2560/arduino/WMath.cpp.o .build_ano/mega2560/arduino/IPAddress.cpp.o .build_ano/mega2560/arduino/WString.cpp.o .build_ano/mega2560/arduino/CDC.cpp.o .build_ano/mega2560/arduino/HardwareSerial.cpp.o .build_ano/mega2560/arduino/new.cpp.o .build_ano/mega2560/arduino/main.cpp.o .build_ano/mega2560/arduino/Tone.cpp.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/mega2560/src/sketch.ino.cpp.o : .build_ano/mega2560/src/sketch.ino.cpp
	@echo [93msrc/sketch.ino.cpp[0m
	@mkdir -p .build_ano/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master" -I"/usr/share/arduino/libraries/Adafruit_Motor_Shield_V2_Library-master/utility" -I"/usr/share/arduino/libraries/Wire" -I"/usr/share/arduino/libraries/Wire/utility" -I"/usr/share/arduino/hardware/arduino/cores/arduino" -I"/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc" -fno-exceptions -iquote src  -o $@ -c .build_ano/mega2560/src/sketch.ino.cpp
include .build_ano/mega2560/src/sketch.ino.cpp.d















.build_ano/mega2560/firmware.elf : .build_ano/mega2560/src/sketch.ino.cpp.o .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/libAdafruit_Motor_Shield_V2_Library-master.a .build_ano/mega2560/Wire/libWire.a .build_ano/mega2560/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/mega2560/firmware.hex : .build_ano/mega2560/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/mega2560/src/dependencies.d .build_ano/mega2560/arduino/dependencies.d .build_ano/mega2560/Adafruit_Motor_Shield_V2_Library-master/dependencies.d .build_ano/mega2560/Wire/dependencies.d

all : .build_ano/mega2560/firmware.hex
	@true

